version: '3.3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "9000:9000"
    networks:
      - my_network

  nginx_server:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
    networks:
      - my_network
    depends_on:
      - app

networks:
  my_network:
    driver: bridge

