FROM nginx:stable

COPY nginx.conf /etc/nginx/nginx.conf

COPY fullchain.pem /etc/nginx/certs/fullchain.pem
COPY privkey.pem /etc/nginx/certs/privkey.pem

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
